schema_version = "1.0.0"
id = "slides_pro"
version = "1.6.0"
name = "Slides PRO"
tagline = "Create and play slide-based presentations in the 3D View"
maintainer = "Alessandro Pannoli"
type = "add-on"
tags = ["3D View"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/AlessandroPannoli/slides-pro"
copyright = ["2026 Alessandro Pannoli"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
  "*.rar",
  "*.pyc",
  "*.blend1",
  "README*",
  "CHANGELOG*",
  "SUPPORT*",
  "EXTENSION_SUBMISSION_TEXTS.md",
]
